name: Release

on:
    push:
        tags:
            - v*

jobs:
    release:
        if: github.repository == 'braebo/ansi'
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write # to create release (changesets/action)
            pull-requests: write # to create pull request (changesets/action)
            id-token: write # required for JSR
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # Fetch the entire git history so Changesets can generate changelogs with the correct commits
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  registry-url: https://registry.npmjs.org
                  node-version: lts/*

            - name: Setup PNPM
              uses: pnpm/action-setup@v3.0.0
              with:
                  version: 8.15.7

            - name: Install
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Check
              run: pnpm check

            - name: changelogithub
              run: pnpm dlx changelogithub@0.12
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Publish to NPM
              run: |
                  pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
                  pnpm publish --no-git-checks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true

            - name: Publish to jsr
              run: pnpm jsr publish
